/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CETHTokenInterface,
  CETHTokenInterfaceInterface,
} from "../CETHTokenInterface";

const _abi = [
  {
    inputs: [],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class CETHTokenInterface__factory {
  static readonly abi = _abi;
  static createInterface(): CETHTokenInterfaceInterface {
    return new utils.Interface(_abi) as CETHTokenInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CETHTokenInterface {
    return new Contract(address, _abi, signerOrProvider) as CETHTokenInterface;
  }
}
