/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { INapierRouter, INapierRouterInterface } from "../INapierRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nPT",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minLpTokenOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "addLiquidityFromUnderlying",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INapierRouter__factory {
  static readonly abi = _abi;
  static createInterface(): INapierRouterInterface {
    return new utils.Interface(_abi) as INapierRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INapierRouter {
    return new Contract(address, _abi, signerOrProvider) as INapierRouter;
  }
}
