/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolAddressesProvider,
  IPoolAddressesProviderInterface,
} from "../IPoolAddressesProvider";

const _abi = [
  {
    inputs: [],
    name: "getPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPoolAddressesProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolAddressesProviderInterface {
    return new utils.Interface(_abi) as IPoolAddressesProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolAddressesProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPoolAddressesProvider;
  }
}
