[profile.default]
via_ir = false
out = 'out'
libs = ["lib"]
remappings = [
    'forge-std=lib/forge-std/src/',
    'solmate=lib/solmate/src/',
]
optimizer_runs = 200

[profile.optimized]
solc = '0.8.6'
