/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestAaveAdapterADAI } from "./TestAaveAdapterADAI";
export type { TestAaveAdapterCDAI } from "./TestAaveAdapterCDAI";
