/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClaim } from "./IClaim";
export type { IZero } from "./IZero";
export type { Tranche } from "./Tranche";
