/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestAaveAdapterADAI__factory } from "./TestAaveAdapterADAI__factory";
export { TestAaveAdapterCDAI__factory } from "./TestAaveAdapterCDAI__factory";
